language: android
jdk: oraclejdk8
sudo: required

branches:
  except:
  - gh-pages

env:
  global:
  - ANDROID_API=27
  - ANDROID_BUILD_TOOLS=27.0.3

before_install:
- openssl aes-256-cbc -K $encrypted_868c327d9afa_key -iv $encrypted_868c327d9afa_iv -in travis.properties.enc -out travis.properties -d
- cp travis.properties local.properties

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"

android:
  components:
  - build-tools-${ANDROID_BUILD_TOOLS}
  - android-${ANDROID_API}
  - extra-google-m2repository
  - extra-android-m2repository

script:
- ./gradlew build
- ./gradlew test

before_deploy:
- export DEPLOY_AAR=$(ls **/build/outputs/aar/content-sdk-*-release.aar)
- export DEPLOY_MAPPING=$(ls **/build/outputs/mapping/release/mapping.txt)
- export DEPLOY_JAVADOC=$(ls **/build/libs/content-sdk-*-javadoc.jar)

deploy:
  # Bintray
  - provider: script
    script: bash ./gradlew bintrayUpload
    skip_cleanup: true
    on:
      repo: glomex/content-sdk-android
      tags: true
  # Github releases
  - provider: releases
    api_key:
      secure: ${GITHUB_API_KEY}
    file:
      - "${DEPLOY_AAR}"
      - "${DEPLOY_MAPPING}"
      - "${DEPLOY_JAVADOC}"
    skip_cleanup: true
    on:
      repo: glomex/content-sdk-android
      tags: true